"""Fund portfolios data — Top institutional investors' holdings from 13F filings."""

FUND_PORTFOLIOS = {
    "Berkshire Hathaway (Warren Buffett)": {
        "cik": "0001067983",
        "aum": "$350B+",
        "strategy": "Value investing, concentrated positions, long-term holdings",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "AAPL", "name": "Apple Inc", "weight": 44.5, "sector": "Technology"},
            {"ticker": "BAC", "name": "Bank of America", "weight": 10.1, "sector": "Financial Services"},
            {"ticker": "AXP", "name": "American Express", "weight": 8.2, "sector": "Financial Services"},
            {"ticker": "KO", "name": "Coca-Cola", "weight": 7.5, "sector": "Consumer Defensive"},
            {"ticker": "CVX", "name": "Chevron", "weight": 5.8, "sector": "Energy"},
            {"ticker": "OXY", "name": "Occidental Petroleum", "weight": 4.2, "sector": "Energy"},
            {"ticker": "KHC", "name": "Kraft Heinz", "weight": 3.5, "sector": "Consumer Defensive"},
            {"ticker": "MCO", "name": "Moody's Corp", "weight": 2.8, "sector": "Financial Services"},
            {"ticker": "DVA", "name": "DaVita Inc", "weight": 1.5, "sector": "Healthcare"},
            {"ticker": "CB", "name": "Chubb Limited", "weight": 1.4, "sector": "Financial Services"},
            {"ticker": "ATVI", "name": "Activision Blizzard", "weight": 1.2, "sector": "Technology"},
            {"ticker": "HPQ", "name": "HP Inc", "weight": 1.0, "sector": "Technology"},
            {"ticker": "PARA", "name": "Paramount Global", "weight": 0.8, "sector": "Communication"},
            {"ticker": "SNOW", "name": "Snowflake Inc", "weight": 0.7, "sector": "Technology"},
            {"ticker": "NU", "name": "Nu Holdings", "weight": 0.6, "sector": "Financial Services"},
        ],
    },
    "Bridgewater Associates (Ray Dalio)": {
        "cik": "0001350694",
        "aum": "$125B+",
        "strategy": "Global macro, risk parity, diversified across asset classes",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "SPY", "name": "SPDR S&P 500 ETF", "weight": 14.2, "sector": "ETF"},
            {"ticker": "IVV", "name": "iShares Core S&P 500", "weight": 8.5, "sector": "ETF"},
            {"ticker": "EEM", "name": "iShares MSCI Emerging Mkts", "weight": 7.8, "sector": "ETF"},
            {"ticker": "GLD", "name": "SPDR Gold Shares", "weight": 7.1, "sector": "Commodities"},
            {"ticker": "VWO", "name": "Vanguard FTSE Emerging Mkts", "weight": 6.4, "sector": "ETF"},
            {"ticker": "IEMG", "name": "iShares Core MSCI EM", "weight": 5.2, "sector": "ETF"},
            {"ticker": "PG", "name": "Procter & Gamble", "weight": 4.5, "sector": "Consumer Defensive"},
            {"ticker": "JNJ", "name": "Johnson & Johnson", "weight": 4.1, "sector": "Healthcare"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 3.8, "sector": "Technology"},
            {"ticker": "NVDA", "name": "NVIDIA Corp", "weight": 3.5, "sector": "Technology"},
            {"ticker": "WMT", "name": "Walmart Inc", "weight": 3.2, "sector": "Consumer Defensive"},
            {"ticker": "KO", "name": "Coca-Cola", "weight": 2.9, "sector": "Consumer Defensive"},
            {"ticker": "PEP", "name": "PepsiCo Inc", "weight": 2.6, "sector": "Consumer Defensive"},
            {"ticker": "TLT", "name": "iShares 20+ Year Treasury", "weight": 2.3, "sector": "ETF"},
        ],
    },
    "Renaissance Technologies": {
        "cik": "0001037389",
        "aum": "$80B+",
        "strategy": "Quantitative, algorithmic trading, statistical arbitrage",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "NVDA", "name": "NVIDIA Corp", "weight": 8.2, "sector": "Technology"},
            {"ticker": "META", "name": "Meta Platforms", "weight": 6.5, "sector": "Technology"},
            {"ticker": "MSFT", "name": "Microsoft Corp", "weight": 5.8, "sector": "Technology"},
            {"ticker": "AAPL", "name": "Apple Inc", "weight": 5.1, "sector": "Technology"},
            {"ticker": "AMZN", "name": "Amazon.com", "weight": 4.7, "sector": "Consumer Cyclical"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 4.3, "sector": "Technology"},
            {"ticker": "NFLX", "name": "Netflix Inc", "weight": 3.2, "sector": "Communication"},
            {"ticker": "AVGO", "name": "Broadcom Inc", "weight": 2.9, "sector": "Technology"},
            {"ticker": "UNH", "name": "UnitedHealth Group", "weight": 2.6, "sector": "Healthcare"},
            {"ticker": "NVO", "name": "Novo Nordisk", "weight": 2.3, "sector": "Healthcare"},
            {"ticker": "LLY", "name": "Eli Lilly", "weight": 2.1, "sector": "Healthcare"},
            {"ticker": "V", "name": "Visa Inc", "weight": 1.9, "sector": "Financial Services"},
            {"ticker": "MA", "name": "Mastercard Inc", "weight": 1.7, "sector": "Financial Services"},
            {"ticker": "TSLA", "name": "Tesla Inc", "weight": 1.5, "sector": "Consumer Cyclical"},
        ],
    },
    "Soros Fund Management": {
        "cik": "0001029160",
        "aum": "$25B+",
        "strategy": "Global macro, event-driven, currency & equity plays",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "MSFT", "name": "Microsoft Corp", "weight": 9.8, "sector": "Technology"},
            {"ticker": "AMZN", "name": "Amazon.com", "weight": 7.5, "sector": "Consumer Cyclical"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 6.2, "sector": "Technology"},
            {"ticker": "LLY", "name": "Eli Lilly", "weight": 5.4, "sector": "Healthcare"},
            {"ticker": "NVDA", "name": "NVIDIA Corp", "weight": 4.8, "sector": "Technology"},
            {"ticker": "CRM", "name": "Salesforce Inc", "weight": 4.1, "sector": "Technology"},
            {"ticker": "UBER", "name": "Uber Technologies", "weight": 3.6, "sector": "Technology"},
            {"ticker": "ABNB", "name": "Airbnb Inc", "weight": 3.2, "sector": "Consumer Cyclical"},
            {"ticker": "SNOW", "name": "Snowflake Inc", "weight": 2.8, "sector": "Technology"},
            {"ticker": "RIVN", "name": "Rivian Automotive", "weight": 2.3, "sector": "Consumer Cyclical"},
            {"ticker": "DDOG", "name": "Datadog Inc", "weight": 2.1, "sector": "Technology"},
            {"ticker": "SPOT", "name": "Spotify Technology", "weight": 1.8, "sector": "Communication"},
        ],
    },
    "ARK Invest (Cathie Wood)": {
        "cik": "0001697748",
        "aum": "$15B+",
        "strategy": "Disruptive innovation, high-growth tech, concentrated bets",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "TSLA", "name": "Tesla Inc", "weight": 13.5, "sector": "Consumer Cyclical"},
            {"ticker": "COIN", "name": "Coinbase Global", "weight": 8.2, "sector": "Financial Services"},
            {"ticker": "ROKU", "name": "Roku Inc", "weight": 7.1, "sector": "Communication"},
            {"ticker": "PLTR", "name": "Palantir Technologies", "weight": 6.4, "sector": "Technology"},
            {"ticker": "SQ", "name": "Block Inc", "weight": 5.8, "sector": "Financial Services"},
            {"ticker": "RBLX", "name": "Roblox Corp", "weight": 5.2, "sector": "Technology"},
            {"ticker": "PATH", "name": "UiPath Inc", "weight": 4.5, "sector": "Technology"},
            {"ticker": "SHOP", "name": "Shopify Inc", "weight": 4.1, "sector": "Technology"},
            {"ticker": "DKNG", "name": "DraftKings Inc", "weight": 3.8, "sector": "Consumer Cyclical"},
            {"ticker": "ZM", "name": "Zoom Video", "weight": 3.4, "sector": "Technology"},
            {"ticker": "U", "name": "Unity Software", "weight": 3.0, "sector": "Technology"},
            {"ticker": "CRSP", "name": "CRISPR Therapeutics", "weight": 2.6, "sector": "Healthcare"},
            {"ticker": "TWLO", "name": "Twilio Inc", "weight": 2.3, "sector": "Technology"},
            {"ticker": "BEAM", "name": "Beam Therapeutics", "weight": 1.9, "sector": "Healthcare"},
        ],
    },
    "Bill & Melinda Gates Foundation": {
        "cik": "0001166559",
        "aum": "$42B+",
        "strategy": "Concentrated value, diversified sectors, long-term endowment",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "BRK-B", "name": "Berkshire Hathaway B", "weight": 22.5, "sector": "Financial Services"},
            {"ticker": "MSFT", "name": "Microsoft Corp", "weight": 14.8, "sector": "Technology"},
            {"ticker": "WMT", "name": "Walmart Inc", "weight": 10.2, "sector": "Consumer Defensive"},
            {"ticker": "CAT", "name": "Caterpillar Inc", "weight": 7.6, "sector": "Industrials"},
            {"ticker": "WM", "name": "Waste Management", "weight": 6.4, "sector": "Industrials"},
            {"ticker": "CNI", "name": "Canadian Natl Railway", "weight": 5.1, "sector": "Industrials"},
            {"ticker": "ECL", "name": "Ecolab Inc", "weight": 4.3, "sector": "Basic Materials"},
            {"ticker": "FDX", "name": "FedEx Corp", "weight": 3.8, "sector": "Industrials"},
            {"ticker": "SCHW", "name": "Charles Schwab", "weight": 3.2, "sector": "Financial Services"},
            {"ticker": "CCI", "name": "Crown Castle Intl", "weight": 2.7, "sector": "Real Estate"},
            {"ticker": "CVNA", "name": "Carvana Co", "weight": 2.1, "sector": "Consumer Cyclical"},
        ],
    },
    "Pershing Square (Bill Ackman)": {
        "cik": "0001336528",
        "aum": "$18B+",
        "strategy": "Concentrated activist, high-conviction, large-cap quality",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "CMG", "name": "Chipotle Mexican Grill", "weight": 17.5, "sector": "Consumer Cyclical"},
            {"ticker": "HLT", "name": "Hilton Worldwide", "weight": 16.8, "sector": "Consumer Cyclical"},
            {"ticker": "QSR", "name": "Restaurant Brands Intl", "weight": 14.2, "sector": "Consumer Cyclical"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 13.5, "sector": "Technology"},
            {"ticker": "CP", "name": "Canadian Pacific Kansas", "weight": 11.8, "sector": "Industrials"},
            {"ticker": "LOW", "name": "Lowe's Companies", "weight": 9.4, "sector": "Consumer Cyclical"},
            {"ticker": "NFLX", "name": "Netflix Inc", "weight": 8.2, "sector": "Communication"},
            {"ticker": "BN", "name": "Brookfield Corp", "weight": 5.1, "sector": "Financial Services"},
            {"ticker": "NKE", "name": "Nike Inc", "weight": 3.5, "sector": "Consumer Cyclical"},
        ],
    },
    "Appaloosa Management (David Tepper)": {
        "cik": "0001656456",
        "aum": "$20B+",
        "strategy": "Distressed debt, event-driven, mega-cap tech overweight",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "META", "name": "Meta Platforms", "weight": 12.4, "sector": "Technology"},
            {"ticker": "MSFT", "name": "Microsoft Corp", "weight": 10.8, "sector": "Technology"},
            {"ticker": "AMZN", "name": "Amazon.com", "weight": 9.5, "sector": "Consumer Cyclical"},
            {"ticker": "NVDA", "name": "NVIDIA Corp", "weight": 8.7, "sector": "Technology"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 7.2, "sector": "Technology"},
            {"ticker": "AAPL", "name": "Apple Inc", "weight": 6.1, "sector": "Technology"},
            {"ticker": "BABA", "name": "Alibaba Group", "weight": 5.3, "sector": "Consumer Cyclical"},
            {"ticker": "JD", "name": "JD.com Inc", "weight": 4.1, "sector": "Consumer Cyclical"},
            {"ticker": "PDD", "name": "PDD Holdings", "weight": 3.6, "sector": "Consumer Cyclical"},
            {"ticker": "UBER", "name": "Uber Technologies", "weight": 3.2, "sector": "Technology"},
            {"ticker": "PCG", "name": "PG&E Corp", "weight": 2.8, "sector": "Utilities"},
            {"ticker": "ET", "name": "Energy Transfer", "weight": 2.4, "sector": "Energy"},
        ],
    },
    "Greenlight Capital (David Einhorn)": {
        "cik": "0001079114",
        "aum": "$3.5B+",
        "strategy": "Value-oriented, long/short equity, contrarian bets",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "TECK", "name": "Teck Resources", "weight": 12.8, "sector": "Basic Materials"},
            {"ticker": "CNX", "name": "CNX Resources", "weight": 10.5, "sector": "Energy"},
            {"ticker": "CC", "name": "Chemours Co", "weight": 8.4, "sector": "Basic Materials"},
            {"ticker": "GPRE", "name": "Green Plains Inc", "weight": 7.2, "sector": "Consumer Defensive"},
            {"ticker": "ODP", "name": "ODP Corp", "weight": 6.1, "sector": "Consumer Cyclical"},
            {"ticker": "JACK", "name": "Jack in the Box", "weight": 5.5, "sector": "Consumer Cyclical"},
            {"ticker": "BHF", "name": "Brighthouse Financial", "weight": 4.8, "sector": "Financial Services"},
            {"ticker": "BATRA", "name": "Atlanta Braves Holdings", "weight": 4.2, "sector": "Communication"},
            {"ticker": "KNTK", "name": "Kinetik Holdings", "weight": 3.6, "sector": "Energy"},
            {"ticker": "PRDO", "name": "Perdoceo Education", "weight": 3.1, "sector": "Consumer Cyclical"},
            {"ticker": "CHNG", "name": "Change Healthcare", "weight": 2.7, "sector": "Healthcare"},
            {"ticker": "WBA", "name": "Walgreens Boots", "weight": 2.3, "sector": "Healthcare"},
        ],
    },
    "Tiger Global Management": {
        "cik": "0001167483",
        "aum": "$30B+",
        "strategy": "Growth tech, internet platforms, global technology leaders",
        "last_updated": "Q4 2025 13F",
        "holdings": [
            {"ticker": "MSFT", "name": "Microsoft Corp", "weight": 12.5, "sector": "Technology"},
            {"ticker": "META", "name": "Meta Platforms", "weight": 10.8, "sector": "Technology"},
            {"ticker": "GOOGL", "name": "Alphabet Inc", "weight": 8.4, "sector": "Technology"},
            {"ticker": "AMZN", "name": "Amazon.com", "weight": 7.6, "sector": "Consumer Cyclical"},
            {"ticker": "SE", "name": "Sea Limited", "weight": 6.2, "sector": "Technology"},
            {"ticker": "CRWD", "name": "CrowdStrike Holdings", "weight": 5.5, "sector": "Technology"},
            {"ticker": "SNOW", "name": "Snowflake Inc", "weight": 4.8, "sector": "Technology"},
            {"ticker": "NET", "name": "Cloudflare Inc", "weight": 4.1, "sector": "Technology"},
            {"ticker": "MNDY", "name": "Monday.com Ltd", "weight": 3.5, "sector": "Technology"},
            {"ticker": "PANW", "name": "Palo Alto Networks", "weight": 3.2, "sector": "Technology"},
            {"ticker": "DDOG", "name": "Datadog Inc", "weight": 2.8, "sector": "Technology"},
            {"ticker": "ZS", "name": "Zscaler Inc", "weight": 2.4, "sector": "Technology"},
            {"ticker": "BILL", "name": "BILL Holdings", "weight": 2.1, "sector": "Technology"},
        ],
    },
}
